export {
  ApiError,
  ReauthenticationRedirectError,
  apiRequest,
  configureApiClient,
  loginWithPassword,
  resetApiClientForTests,
  setCsrfToken,
} from "./client";
export type { ApiClientConfig, ApiFetch } from "./client";

export {
  DEFAULT_PAGE_SIZE,
  addAdminVaultMember,
  addVaultMember,
  approveRecover,
  cancelJob,
  cancelUpload,
  confirmRecoveryCustody,
  createAdminUser,
  createAdminVault,
  createVault,
  deleteLifecycleFolderOverride,
  estimateRecover,
  exportAdminVaultRecovery,
  exportRecoverySecret,
  fetchAdminUsers,
  fetchAdminVaultMembers,
  fetchAdminVaultQuotas,
  fetchAdminVaults,
  fetchCloudDeletion,
  fetchFileHistory,
  fetchFileVersions,
  fetchFiles,
  fetchI18nCatalog,
  fetchJobs,
  fetchLifecycle,
  fetchMe,
  fetchOperationPolicy,
  fetchStats,
  fetchVaultMembers,
  fetchVaultQuotas,
  fetchVaults,
  lookupVaultUser,
  logout,
  previewCloudDeletion,
  previewOperationGlobs,
  removeAdminVaultMember,
  removeVaultMember,
  selectVault,
  startCloudArchive,
  startCloudPurge,
  startFreeSpace,
  startRecover,
  startUpload,
  transferAdminVaultOwner,
  transferVaultOwner,
  updateAdminUser,
  updateAdminVaultQuotas,
  updateCloudDeletion,
  updateLifecycleDefault,
  updateLocale,
  updateOperationPolicy,
  upsertLifecycleFolderOverride,
} from "./endpoints";

export { createLatestRequestScope } from "./latest";
export type { LatestRequestHandle, LatestRequestScope } from "./latest";

export {
  ACTIVE_JOB_POLL_MS,
  IDLE_POLL_MS,
  jobAwareRefetchInterval,
  jobPollIntervalMs,
} from "./polling";

export {
  ApiQueryProvider,
  apiQueryKeys,
  createAppQueryClient,
  fileHistoryQueryOptions,
  filesQueryOptions,
  i18nCatalogQueryOptions,
  jobsQueryOptions,
  jobsRefetchInterval,
  meQueryOptions,
  statsQueryOptions,
  vaultsQueryOptions,
} from "./query";

export type {
  AdminMembershipCreatePayload,
  AdminOwnerTransferPayload,
  AdminUser,
  AdminUserCreatePayload,
  AdminUsersResponse,
  AdminUserUpdatePayload,
  AdminVault,
  AdminVaultCreatePayload,
  AdminVaultMember,
  AdminVaultMembersResponse,
  AdminVaultsResponse,
  ArchiveListItem,
  ArchiveVersionItem,
  ArchiveVersionSummary,
  AuthMethod,
  CloudDeletionPreview,
  CloudDeletionSettings,
  CloudPurgePayload,
  DirectoryListItem,
  EncryptionMode,
  FileHistoryResponse,
  FileOperationAction,
  FileOperationPayload,
  FileOperationResponse,
  FileVersionsResponse,
  FilesQuery,
  FilesResponse,
  FilesystemCheck,
  FilesystemFinding,
  FilesystemHealth,
  GlobPreviewResponse,
  I18nCatalogResponse,
  JobCancelPayload,
  JobCancelResponse,
  JobGroup,
  JobRecord,
  JobStatus,
  JobsResponse,
  LifecycleGuidedProfile,
  LifecycleResponse,
  LocaleUpdateResponse,
  MeResponse,
  MeVault,
  OperationPolicy,
  PathHistoryEntry,
  QuotaDecision,
  QuotaEvaluation,
  QuotaLimits,
  QuotaUsage,
  RecoverEstimateResponse,
  RecoveryConfirmRequest,
  RecoveryConfirmResponse,
  RecoveryExportRequest,
  RecoveryExportResponse,
  RestoreEstimate,
  StatsResponse,
  UserLookupResult,
  VaultCreateRequest,
  VaultCreateResponse,
  VaultFileListItem,
  VaultListItem,
  VaultMember,
  VaultMembersResponse,
  VaultQuotaUpdatePayload,
  VaultQuotasResponse,
  VaultRole,
  VaultSelectRequest,
  VaultSelectResponse,
  VaultsResponse,
} from "./types";
