#!/usr/bin/env bash
# Generated by Quality Playbook v1.5.10 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-07-24 · Project: FrostVault
# Mechanical enumeration check for process_job action/status dispatcher branches.
set -euo pipefail
# Canonical layout (v1.5.7+): quality/mechanical/ at the quality root (no workspace/).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CASES="$ROOT/quality/mechanical/process_job_action_branches.txt"
STORAGE="$ROOT/app/storage.py"
RECEIPT="$ROOT/quality/mechanical/verify_receipt.txt"

: >"$RECEIPT"
echo "mechanical verify: process_job dispatcher" | tee -a "$RECEIPT"
echo "storage=$STORAGE" | tee -a "$RECEIPT"

required=(
  'job["action"] == "upload" and job["status"] in {"queued", "retrying"}'
  'job["action"] == "rename" and job["status"] == "queued"'
  'job["action"] == "recover"'
  'job["action"] == "free-space" and job["status"] == "queued"'
  'job["action"] == "cloud-archive" and job["status"] == "queued"'
  'job["action"] == "cloud-purge" and job["status"] in'
)

fail=0
for needle in "${required[@]}"; do
  if grep -F -q "$needle" "$STORAGE"; then
    echo "FOUND: $needle" | tee -a "$RECEIPT"
  else
    echo "MISSING: $needle" | tee -a "$RECEIPT"
    fail=1
  fi
done

if grep -F -q 'job["action"] == "recover" and job["status"]' "$STORAGE"; then
  echo "FOUND recover status conjunct (REQ-002 satisfied in code)" | tee -a "$RECEIPT"
else
  echo "GAP: recover has no status conjunct (REQ-002 candidate)" | tee -a "$RECEIPT"
fi

STORAGE="$STORAGE" CASES="$CASES" python3 - <<'PY'
import os
from pathlib import Path
storage = Path(os.environ["STORAGE"])
out = Path(os.environ["CASES"])
lines = storage.read_text().splitlines()
base = next(i for i,l in enumerate(lines,1) if l.startswith("def process_job("))
end = next(i for i,l in enumerate(lines,1) if i>base and l.startswith("def process_jobs_once"))
rows=[]
for i in range(base, end):
    s=lines[i-1].strip()
    if s.startswith("if job[\"action\"]") or s.startswith("elif job[\"action\"]"):
        rows.append(f"{i}: {s}")
out.write_text("\n".join(rows)+"\n")
print(f"wrote {out} ({len(rows)} branches)")
PY

if [[ "$fail" -ne 0 ]]; then
  echo "VERIFY FAIL" | tee -a "$RECEIPT"
  exit 1
fi
echo "VERIFY OK (gaps may still be noted above)" | tee -a "$RECEIPT"
exit 0
