# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-07-23 · Project: FrostVault
"""Regression tests for Phase 3 confirmed bugs.

Each test asserts the *desired correct* behavior and is marked
``@unittest.expectedFailure`` while the bug remains open. Do not rewrite
these to assert the broken behavior.

Run from repo root:
  PYTHONPATH=. .venv/bin/python -m unittest discover -s quality -p 'test_regression.py' -v
"""
from __future__ import annotations

import inspect
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

from app.database import SQLiteConnection
from app.sessions import create_session, csrf_token_for, resolve_session
from tests.test_database import run_alembic


REPO_ROOT = Path(__file__).resolve().parents[1]
STORAGE_PY = (REPO_ROOT / "app" / "storage.py").read_text(encoding="utf-8")
SESSIONS_PY = (REPO_ROOT / "app" / "sessions.py").read_text(encoding="utf-8")
METADATA_PY = (
    REPO_ROOT / "app" / "services" / "metadata_backups.py"
).read_text(encoding="utf-8")
README = (REPO_ROOT / "README.md").read_text(encoding="utf-8")


def _process_job_body() -> str:
    start = STORAGE_PY.index("def process_job")
    end = STORAGE_PY.index("\ndef process_jobs_once", start)
    return STORAGE_PY[start:end]


def _cloud_archive_body() -> str:
    start = STORAGE_PY.index("def process_cloud_archive")
    end = STORAGE_PY.index("\ndef process_cloud_purge", start)
    return STORAGE_PY[start:end]


def _verify_latest_body() -> str:
    start = STORAGE_PY.index("def _verify_latest_metadata_backup_once")
    end = STORAGE_PY.index("\nasync def background_loop", start)
    return STORAGE_PY[start:end]


def _csrf_body() -> str:
    start = SESSIONS_PY.index("def csrf_token_for")
    end = SESSIONS_PY.index("\ndef mark_reauthenticated", start)
    return SESSIONS_PY[start:end]


class TestBug001(unittest.TestCase):
    """BUG-001: recover dispatcher must whitelist statuses (REQ-002)."""

    @unittest.expectedFailure
    def test_bug_001_recover_requires_status_whitelist(self) -> None:
        """[BUG-001][Req: REQ-002] recover branch must conjunct status set.

        Desired: ``elif job["action"] == "recover" and job["status"] in {...}``
        Current: bare ``elif job["action"] == "recover":`` at storage.py:2223.
        Fix patch: quality/patches/BUG-001-fix.patch
        """
        body = _process_job_body()
        recover_lines = [
            line.strip()
            for line in body.splitlines()
            if 'job["action"] == "recover"' in line or "job['action'] == 'recover'" in line
        ]
        self.assertTrue(recover_lines, "recover branch missing from process_job")
        line = recover_lines[0]
        self.assertIn("status", line)
        self.assertRegex(
            line,
            r"queued.*retrying.*restoring|retrying.*queued.*restoring|restoring.*queued.*retrying",
        )


class TestBug002(unittest.TestCase):
    """BUG-002: cloud-archive must detect concurrent current VersionId (REQ-004)."""

    @unittest.expectedFailure
    def test_bug_002_cloud_archive_detects_concurrent_version(self) -> None:
        """[BUG-002][Req: REQ-004] compare live current VersionId before hide.

        Desired: Head/compare scheduled provider_version_id before unversioned
        delete_object. Current: delete_object(Bucket, Key) only at 2099-2102.
        Fix patch: quality/patches/BUG-002-fix.patch
        """
        body = _cloud_archive_body()
        self.assertIn("delete_object(", body)
        # Desired correct behavior: inspect current generation before marker.
        self.assertTrue(
            ("head_object(" in body) or ("HeadObject" in body),
            "cloud-archive must Head current object before creating delete marker",
        )
        self.assertIn("provider_version_id", body)
        # Scheduled version must be compared to live VersionId (not only loaded).
        self.assertRegex(
            body,
            r"VersionId|provider_version_id.*=|!=.*provider_version_id|provider_version_id.*!=",
        )
        # The delete_object call site must not be the only use of the scheduled id.
        delete_idx = body.index("delete_object(")
        before_delete = body[:delete_idx]
        self.assertTrue(
            "head_object(" in before_delete.lower()
            or "head_object(" in before_delete
            or "HeadObject" in before_delete,
            "Head/compare must occur before delete_object",
        )


class TestBug003(unittest.TestCase):
    """BUG-003: list-only verify must not equal full verified success (REQ-005)."""

    @unittest.expectedFailure
    def test_bug_003_list_only_not_full_verify(self) -> None:
        """[BUG-003][Req: REQ-005] list-only mode must not yield full verify success.

        Desired: createdb-failure path is not ok:True for full verify, OR consumer
        refuses non-temp_database modes before status='verified'.
        Fix patch: quality/patches/BUG-003-fix.patch
        """
        from app.services import metadata_backups

        # Desired producer behavior: list-only is not a successful full verify.
        # We assert the source contract consumers rely on.
        list_only_return = (
            '"ok": True' in METADATA_PY
            and '"verification_mode": "pg_restore_list"' in METADATA_PY
        )
        consumer = _verify_latest_body()
        consumer_checks_mode = (
            "verification_mode" in consumer
            and "temp_database" in consumer
            and "verified" in consumer
        )
        # At least one side must enforce: either producer does not return ok True
        # for list-only, or consumer refuses list-only before marking verified.
        producer_ok_false_for_list = (
            '"verification_mode": "pg_restore_list"' in METADATA_PY
            and '"ok": False' in METADATA_PY[
                METADATA_PY.index("created.returncode != 0") : METADATA_PY.index(
                    '"verification_mode": "pg_restore_list"'
                )
                + 80
            ]
        )
        self.assertTrue(
            producer_ok_false_for_list or consumer_checks_mode,
            "list-only path must not be treated as full verified success",
        )
        # Sanity: helper still exists.
        self.assertTrue(inspect.isfunction(metadata_backups.verify_restore_isolated))


class TestBug004(unittest.TestCase):
    """BUG-004: csrf_token_for must honor session_version (REQ-008)."""

    def setUp(self) -> None:
        self._directory = tempfile.TemporaryDirectory()
        self.addCleanup(self._directory.cleanup)
        self.database_path = Path(self._directory.name) / "csrf.db"
        migrated = run_alembic(self.database_path)
        self.assertEqual(migrated.returncode, 0, migrated.stderr)

    @unittest.expectedFailure
    def test_bug_004_csrf_honors_session_version(self) -> None:
        """[BUG-004][Req: REQ-008] force-logout must invalidate CSRF lookup.

        Desired: after users.session_version bump, csrf_token_for returns None
        just like resolve_session. Current: token still returned (sessions.py:115-137).
        Fix patch: quality/patches/BUG-004-fix.patch
        """
        # Source shape: csrf body must mention session_version (desired).
        self.assertIn(
            "session_version",
            _csrf_body(),
            "csrf_token_for must consult session_version",
        )
        with SQLiteConnection(str(self.database_path)) as connection:
            user = connection.execute(
                """
                INSERT INTO users(username, display_name, password_hash, is_admin, active)
                VALUES ('csrf-user', 'CSRF', 'hash', TRUE, TRUE)
                RETURNING id
                """
            ).fetchone()
            token = create_session(
                connection, user_id=user["id"], auth_method="local"
            )
            self.assertIsNotNone(csrf_token_for(connection, token))
            self.assertIsNotNone(resolve_session(connection, token))
            connection.execute(
                "UPDATE users SET session_version=session_version+1 WHERE id=%s",
                (user["id"],),
            )
            self.assertIsNone(resolve_session(connection, token))
            # Desired correct behavior:
            self.assertIsNone(
                csrf_token_for(connection, token),
                "csrf_token_for must return None after session_version bump",
            )


class TestBug005(unittest.TestCase):
    """BUG-005: README Users must not advertise operator free-space (REQ-003)."""

    @unittest.expectedFailure
    def test_bug_005_readme_users_owner_only_free_space(self) -> None:
        """[BUG-005][Req: REQ-003] Users section must match owner-only free-space.

        Desired: operator capabilities exclude free local space.
        Current: README.md:19-20 claims operator can free local space.
        Fix patch: quality/patches/BUG-005-fix.patch
        """
        users_start = README.index("## Users and vaults")
        users_end = README.index("## Local cleanup safety", users_start)
        users = README[users_start:users_end]
        self.assertNotRegex(
            users,
            r"operator`[^.\n]*free",
            "README Users must not claim operators can free local space",
        )
        # Local cleanup safety remains the authoritative owner-only wording.
        self.assertIn("for owners, and when", README)


if __name__ == "__main__":
    unittest.main()
