# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-07-23 · Project: FrostVault
"""Regression tests for Phase 3–4 confirmed bugs.

Each test asserts the *desired correct* behavior and is marked
``@unittest.expectedFailure`` while the bug remains open. Do not rewrite
these to assert the broken behavior.

Run from repo root:
  PYTHONPATH=. .venv/bin/python -m unittest discover -s quality -p 'test_regression.py' -v
"""
from __future__ import annotations

import inspect
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

from app.database import SQLiteConnection
from app.sessions import create_session, csrf_token_for, resolve_session
from tests.test_database import run_alembic


REPO_ROOT = Path(__file__).resolve().parents[1]
STORAGE_PY = (REPO_ROOT / "app" / "storage.py").read_text(encoding="utf-8")
SESSIONS_PY = (REPO_ROOT / "app" / "sessions.py").read_text(encoding="utf-8")
METADATA_PY = (
    REPO_ROOT / "app" / "services" / "metadata_backups.py"
).read_text(encoding="utf-8")
README = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
CATALOG_PY = (REPO_ROOT / "app" / "catalog.py").read_text(encoding="utf-8")
MAIN_PY = (REPO_ROOT / "app" / "main.py").read_text(encoding="utf-8")


def _process_job_body() -> str:
    start = STORAGE_PY.index("def process_job")
    end = STORAGE_PY.index("\ndef process_jobs_once", start)
    return STORAGE_PY[start:end]


def _cloud_archive_body() -> str:
    start = STORAGE_PY.index("def process_cloud_archive")
    end = STORAGE_PY.index("\ndef process_cloud_purge", start)
    return STORAGE_PY[start:end]


def _verify_latest_body() -> str:
    start = STORAGE_PY.index("def _verify_latest_metadata_backup_once")
    end = STORAGE_PY.index("\nasync def background_loop", start)
    return STORAGE_PY[start:end]


def _csrf_body() -> str:
    start = SESSIONS_PY.index("def csrf_token_for")
    end = SESSIONS_PY.index("\ndef mark_reauthenticated", start)
    return SESSIONS_PY[start:end]


class TestBug001(unittest.TestCase):
    """BUG-001: recover dispatcher must whitelist statuses (REQ-002)."""

    @unittest.expectedFailure
    def test_bug_001_recover_requires_status_whitelist(self) -> None:
        """[BUG-001][Req: REQ-002] recover branch must conjunct status set.

        Desired: ``elif job["action"] == "recover" and job["status"] in {...}``
        Current: bare ``elif job["action"] == "recover":`` at storage.py:2223.
        Fix patch: quality/workspace/patches/BUG-001-fix.patch
        """
        body = _process_job_body()
        recover_lines = [
            line.strip()
            for line in body.splitlines()
            if 'job["action"] == "recover"' in line or "job['action'] == 'recover'" in line
        ]
        self.assertTrue(recover_lines, "recover branch missing from process_job")
        line = recover_lines[0]
        self.assertIn("status", line)
        self.assertRegex(
            line,
            r"queued.*retrying.*restoring|retrying.*queued.*restoring|restoring.*queued.*retrying",
        )


class TestBug002(unittest.TestCase):
    """BUG-002: cloud-archive must detect concurrent current VersionId (REQ-004)."""

    @unittest.expectedFailure
    def test_bug_002_cloud_archive_detects_concurrent_version(self) -> None:
        """[BUG-002][Req: REQ-004] compare live current VersionId before hide.

        Desired: Head/compare scheduled provider_version_id before unversioned
        delete_object. Current: delete_object(Bucket, Key) only at 2099-2102.
        Fix patch: quality/workspace/patches/BUG-002-fix.patch
        """
        body = _cloud_archive_body()
        self.assertIn("delete_object(", body)
        # Desired correct behavior: inspect current generation before marker.
        self.assertTrue(
            ("head_object(" in body) or ("HeadObject" in body),
            "cloud-archive must Head current object before creating delete marker",
        )
        self.assertIn("provider_version_id", body)
        # Scheduled version must be compared to live VersionId (not only loaded).
        self.assertRegex(
            body,
            r"VersionId|provider_version_id.*=|!=.*provider_version_id|provider_version_id.*!=",
        )
        # The delete_object call site must not be the only use of the scheduled id.
        delete_idx = body.index("delete_object(")
        before_delete = body[:delete_idx]
        self.assertTrue(
            "head_object(" in before_delete.lower()
            or "head_object(" in before_delete
            or "HeadObject" in before_delete,
            "Head/compare must occur before delete_object",
        )




class TestBug004(unittest.TestCase):
    """BUG-004: csrf_token_for must honor session_version (REQ-008)."""

    def setUp(self) -> None:
        self._directory = tempfile.TemporaryDirectory()
        self.addCleanup(self._directory.cleanup)
        self.database_path = Path(self._directory.name) / "csrf.db"
        migrated = run_alembic(self.database_path)
        self.assertEqual(migrated.returncode, 0, migrated.stderr)

    @unittest.expectedFailure
    def test_bug_004_csrf_honors_session_version(self) -> None:
        """[BUG-004][Req: REQ-008] force-logout must invalidate CSRF lookup.

        Desired: after users.session_version bump, csrf_token_for returns None
        just like resolve_session. Current: token still returned (sessions.py:115-137).
        Fix patch: quality/workspace/patches/BUG-004-fix.patch
        """
        # Source shape: csrf body must mention session_version (desired).
        self.assertIn(
            "session_version",
            _csrf_body(),
            "csrf_token_for must consult session_version",
        )
        with SQLiteConnection(str(self.database_path)) as connection:
            user = connection.execute(
                """
                INSERT INTO users(username, display_name, password_hash, is_admin, active)
                VALUES ('csrf-user', 'CSRF', 'hash', TRUE, TRUE)
                RETURNING id
                """
            ).fetchone()
            token = create_session(
                connection, user_id=user["id"], auth_method="local"
            )
            self.assertIsNotNone(csrf_token_for(connection, token))
            self.assertIsNotNone(resolve_session(connection, token))
            connection.execute(
                "UPDATE users SET session_version=session_version+1 WHERE id=%s",
                (user["id"],),
            )
            self.assertIsNone(resolve_session(connection, token))
            # Desired correct behavior:
            self.assertIsNone(
                csrf_token_for(connection, token),
                "csrf_token_for must return None after session_version bump",
            )


class TestBug005(unittest.TestCase):
    """BUG-005: README Users must not advertise operator free-space (REQ-003)."""

    @unittest.expectedFailure
    def test_bug_005_readme_users_owner_only_free_space(self) -> None:
        """[BUG-005][Req: REQ-003] Users section must match owner-only free-space.

        Desired: operator capabilities exclude free local space.
        Current: README.md:19-20 claims operator can free local space.
        Fix patch: quality/workspace/patches/BUG-005-fix.patch
        """
        users_start = README.index("## Users and vaults")
        users_end = README.index("## Local cleanup safety", users_start)
        users = README[users_start:users_end]
        self.assertNotRegex(
            users,
            r"operator`[^.\n]*free",
            "README Users must not claim operators can free local space",
        )
        # Local cleanup safety remains the authoritative owner-only wording.
        self.assertIn("for owners, and when", README)


def _cleanup_abandoned_body() -> str:
    start = STORAGE_PY.index("def cleanup_abandoned_restore_files")
    end = STORAGE_PY.index("\ndef reconcile_interrupted_jobs", start)
    return STORAGE_PY[start:end]


def _reconcile_free_space_block() -> str:
    start = STORAGE_PY.index('if job["action"] == "free-space":')
    # End at the shared requeue path after the free-space continue.
    end = STORAGE_PY.index("summary[\"completed\"] += 1", start)
    return STORAGE_PY[start:end]


class TestBug006(unittest.TestCase):
    """BUG-006: startup must not destroy free-space claim files (REQ-009)."""

    @unittest.expectedFailure
    def test_bug_006_startup_preserves_free_space_claims(self) -> None:
        """[BUG-006][Req: REQ-009] cleanup claims must survive startup reconciliation.

        Desired: ``cleanup_abandoned_restore_files`` must not unlink
        ``.cleanup-*.tmp`` claim files (or reconcile must restore them before
        any cleanup). Current: ``is_restore_temporary_name`` includes cleanup
        claims and startup cleanup deletes them before reconcile marks missing
        paths completed.
        Fix patch: quality/workspace/patches/BUG-006-fix.patch
        """
        cleanup = _cleanup_abandoned_body()
        # Desired: startup cleanup must not treat free-space claims as disposable
        # restore residues. Exclude CLEANUP_TEMPORARY_RE / is_restore_temporary_name
        # for cleanup claims, or never call a predicate that matches them.
        deletes_cleanup_claims = (
            "is_restore_temporary_name" in cleanup
            or "CLEANUP_TEMPORARY_RE" in cleanup
        )
        self.assertFalse(
            deletes_cleanup_claims,
            "cleanup_abandoned_restore_files must not delete .cleanup-*.tmp claims",
        )
        reconcile = _reconcile_free_space_block()
        self.assertIn(
            "restore_claimed_local_copy",
            reconcile,
            "reconcile free-space missing-path path must attempt claim restore",
        )


class TestBug007(unittest.TestCase):
    """BUG-007: operating windows must compare HH:MM as times (REQ-012)."""

    @unittest.expectedFailure
    def test_bug_007_windows_compare_as_times_not_strings(self) -> None:
        """[BUG-007][Req: REQ-012] non-padded inverted windows must be rejected.

        Desired: compare parsed hour/minute (or zero-padded canonical strings)
        so ``start=10:00,end=9:30`` raises and ``start=9:30,end=10:00`` accepts.
        Current: lexicographic ``start >= end`` at operation_policies.py:96-97.
        Fix patch: quality/workspace/patches/BUG-007-fix.patch
        """
        from app.services import operation_policies

        # Desired: inverted non-padded window rejected (REQ-012 CoS 2).
        with self.assertRaises(ValueError):
            operation_policies._normalize_windows(
                [{"weekday": 1, "start": "10:00", "end": "9:30"}]
            )
        # Desired: valid non-padded morning window accepted (HTTP allows len 4–5).
        ok = operation_policies._normalize_windows(
            [{"weekday": 1, "start": "9:30", "end": "10:00"}]
        )
        self.assertEqual(ok[0]["start"], "9:30")
        self.assertEqual(ok[0]["end"], "10:00")


def _record_archive_version_body() -> str:
    start = CATALOG_PY.index("def record_archive_version")
    end = CATALOG_PY.index("\n    def ", start + 1)
    return CATALOG_PY[start:end]


def _confirm_rename_audit_snippet() -> str:
    start = MAIN_PY.index("def confirm_rename")
    end = MAIN_PY.index("\n@app.post", start)
    return MAIN_PY[start:end]


def _oidc_callback_session_branch() -> str:
    start = MAIN_PY.index("user_id = _resolve_or_bind_identity")
    end = MAIN_PY.index("redirect = RedirectResponse", start)
    return MAIN_PY[start:end]


class TestBug008(unittest.TestCase):
    """BUG-008: cloud scan must not fork Vault File identity after rename (REQ-020)."""

    @unittest.expectedFailure
    def test_bug_008_cloud_record_reuses_identity_before_create(self) -> None:
        """[BUG-008][Req: REQ-020] Path History identity survives cloud rediscovery.

        Desired: ``record_archive_version`` dedupes by object_key/VersionId before
        minting a Vault File, and resolves historical Path History for active
        files. Current: ``_get_or_create_file`` runs first and only matches
        ``valid_to IS NULL`` paths, creating orphans on post-rename scans.
        Fix patch: quality/workspace/patches/BUG-008-fix.patch
        """
        body = _record_archive_version_body()
        create_idx = body.find("_get_or_create_file")
        resolve_idx = body.find("_resolve_cloud_path_file")
        existing_idx = body.find("SELECT id FROM archive_versions")
        self.assertGreaterEqual(existing_idx, 0, "must look up existing archive versions")
        # Desired: existing object_key lookup precedes any identity create/resolve.
        first_create = create_idx if create_idx >= 0 else resolve_idx
        self.assertGreaterEqual(first_create, 0, "must resolve or create a Vault File")
        self.assertLess(
            existing_idx,
            first_create,
            "archive_versions object_key lookup must run before Vault File minting",
        )
        self.assertIn(
            "_resolve_cloud_path_file",
            CATALOG_PY,
            "cloud path resolution must consult Path History for active files",
        )


class TestBug009(unittest.TestCase):
    """BUG-009: rename audits must persist via connection (REQ-021)."""

    @unittest.expectedFailure
    def test_bug_009_rename_audit_passes_connection(self) -> None:
        """[BUG-009][Req: REQ-021] Path History mutations must durable-audit.

        Desired: ``audit_log(..., connection, ...)`` inside confirm rename /
        folder rename so ``audit_events`` receives the row. Current: connection
        omitted → log-only.
        Fix patch: quality/workspace/patches/BUG-009-fix.patch
        """
        snippet = _confirm_rename_audit_snippet()
        self.assertIn('audit_log(\n            "vault_file_renamed"', snippet)
        # Desired positional connection argument immediately after event name.
        self.assertRegex(
            snippet,
            r'audit_log\(\s*"vault_file_renamed",\s*connection\s*,',
            "confirm_rename must pass connection to audit_log",
        )
        folder = MAIN_PY[
            MAIN_PY.index("def confirm_folder_rename") : MAIN_PY.index(
                "\n@app.post", MAIN_PY.index("def confirm_folder_rename")
            )
        ]
        self.assertRegex(
            folder,
            r'audit_log\(\s*"vault_folder_renamed",\s*connection\s*,',
            "confirm_folder_rename must pass connection to audit_log",
        )


class TestBug010(unittest.TestCase):
    """BUG-010: configured S3 backup failures must not become None success (REQ-022)."""

    @unittest.expectedFailure
    def test_bug_010_configured_store_failure_raises(self) -> None:
        """[BUG-010][Req: REQ-022] configured bucket client errors fail closed.

        Desired: when ``VAULT_S3_BUCKET`` is set and ``s3_client`` raises,
        ``default_object_store`` raises ``BackupError`` (not ``None``).
        Current: bare ``except Exception: return None``.
        Fix patch: quality/workspace/patches/BUG-010-fix.patch
        """
        start = METADATA_PY.index("def default_object_store")
        end = METADATA_PY.index("\nclass BackupError", start)
        body = METADATA_PY[start:end]
        self.assertIn("raise BackupError", body)
        self.assertNotRegex(
            body,
            r"except Exception:\s*\n\s*return None",
            "configured-store failures must not collapse to None",
        )

class TestBug011(unittest.TestCase):
    """BUG-011: OIDC must not switch sessions on foreign already-linked identity (REQ-023)."""

    @unittest.expectedFailure
    def test_bug_011_oidc_rejects_cross_account_switch(self) -> None:
        """[BUG-011][Req: REQ-023] active Session must not be replaced by foreign identity.

        Desired: when ``resolve_session`` user ≠ resolved identity user, callback
        raises 403 instead of ``create_session`` for the other user.
        Current: else-branch always mints a new session for ``user_id``.
        Fix patch: quality/workspace/patches/BUG-011-fix.patch
        """
        body = _oidc_callback_session_branch()
        self.assertIn('existing and existing["user"]["id"] == user_id', body)
        self.assertRegex(
            body,
            r'elif existing and existing\["user"\]\["id"\] != user_id',
            "callback must explicitly reject cross-account identity while logged in",
        )
        self.assertIn("HTTPException", body)
        self.assertIn("sign out first", body.lower())


def _process_recover_body() -> str:
    start = STORAGE_PY.index("def process_recover")
    end = STORAGE_PY.index("\ndef process_cloud_archive", start)
    return STORAGE_PY[start:end]


def _download_exact_body() -> str:
    start = STORAGE_PY.index("def download_exact_version_plaintext")
    end = STORAGE_PY.index("\ndef process_recover", start)
    return STORAGE_PY[start:end]


def _update_user_body() -> str:
    start = MAIN_PY.index("def update_user")
    end = MAIN_PY.index("\n@app.get", start)
    return MAIN_PY[start:end]


class TestBug012(unittest.TestCase):
    """BUG-012: recover must refuse existing on-disk destination (REQ-024)."""

    @unittest.expectedFailure
    def test_bug_012_recover_refuses_existing_destination(self) -> None:
        """[BUG-012][Req: REQ-024] do not Path.replace over an existing file.

        Desired: before ``temporary.replace(destination)``, refuse when the
        destination already exists on disk (catalog lag / external recreate).
        Current: only catalog ``local_presence == 'present'`` is checked.
        Fix patch: quality/workspace/patches/BUG-012-fix.patch
        """
        body = _process_recover_body()
        self.assertIn("temporary.replace(destination)", body)
        self.assertRegex(
            body,
            r"(os\.path\.lexists\(destination\)|destination\.exists\(\)|"
            r"destination\.is_file\(\)|destination\.is_symlink\(\))",
            "recover must check on-disk destination before replace",
        )


class TestBug013(unittest.TestCase):
    """BUG-013: crypt download must use Archive Version object_key (REQ-025)."""

    @unittest.expectedFailure
    def test_bug_013_crypt_download_uses_object_key(self) -> None:
        """[BUG-013][Req: REQ-025] crypt rclone path derives from object_key.

        Desired: crypt/name-encrypt branch calls ``object_key_to_path`` (or
        otherwise consumes ``object_key``) instead of only ``job['path']``.
        Current: rclone sources use ``job['path']``; ``object_key`` unused.
        Fix patch: quality/workspace/patches/BUG-013-fix.patch
        """
        body = _download_exact_body()
        crypt_idx = body.find("vault_encrypts_names")
        boto_idx = body.find("get_object")
        self.assertGreaterEqual(crypt_idx, 0)
        self.assertGreaterEqual(boto_idx, 0)
        crypt_branch = body[crypt_idx:boto_idx]
        self.assertIn(
            "object_key_to_path",
            crypt_branch,
            "crypt branch must derive logical path from object_key",
        )
        self.assertNotRegex(
            crypt_branch,
            r"configured_rclone_destination\(job,\s*job\[\"path\"\]\)",
            "crypt branch must not hardcode job path as the only address",
        )


class TestBug014(unittest.TestCase):
    """BUG-014: active changes must bump session_version (REQ-026)."""

    @unittest.expectedFailure
    def test_bug_014_active_change_bumps_session_version(self) -> None:
        """[BUG-014][Req: REQ-026] deactivate/reactivate invalidates Sessions.

        Desired: when ``action.active is not None``, updates include
        ``session_version=session_version+1`` (same axis as password change).
        Current: only password changes bump the version.
        Fix patch: quality/workspace/patches/BUG-014-fix.patch
        """
        body = _update_user_body()
        active_block_start = body.index("if action.active is not None")
        password_block_start = body.index("if action.password is not None")
        active_block = body[active_block_start:password_block_start]
        self.assertIn(
            "session_version=session_version+1",
            active_block,
            "active transitions must bump session_version",
        )


class TestBug015(unittest.TestCase):
    """BUG-015: recover high-impact cost must use active price book (REQ-027)."""

    @unittest.expectedFailure
    def test_bug_015_recover_uses_active_price_book(self) -> None:
        """[BUG-015][Req: REQ-027] worker estimate matches recover/estimate book.

        Desired: ``process_recover`` loads ``get_active_price_book`` (or
        ``estimate_restore_cost``) before ``is_high_impact_restore``.
        Current: ``estimate_restore`` uses hardcoded DEFAULT rates only.
        Fix patch: quality/workspace/patches/BUG-015-fix.patch
        """
        body = _process_recover_body()
        impact_idx = body.find("is_high_impact_restore")
        self.assertGreaterEqual(impact_idx, 0)
        prelude = body[:impact_idx]
        self.assertTrue(
            ("get_active_price_book" in prelude)
            or ("estimate_restore_cost" in prelude),
            "high-impact gating must consult the active price book",
        )


def _cancel_recover_body() -> str:
    """Slice of main.py around cancel_jobs recover restore_state handling."""
    # Anchor on cancel_jobs call (stable across BUG-018 fix which removes the
    # recover clear_restore_state block that previously served as the start marker).
    start = MAIN_PY.index("cancel_jobs(job_ids)")
    end = MAIN_PY.index("for row in automatic_cleanup_rows:", start)
    return MAIN_PY[start:end]


def _record_archive_completed_body() -> str:
    cloud = (
        REPO_ROOT / "app" / "services" / "cloud_deletion.py"
    ).read_text(encoding="utf-8")
    start = cloud.index("def record_archive_completed")
    # next top-level def after this one, or EOF-ish
    rest = cloud[start + 4 :]
    next_def = rest.find("\ndef ")
    return cloud[start : start + 4 + next_def] if next_def >= 0 else cloud[start:]


class TestBug016(unittest.TestCase):
    """BUG-016: metadata verify must stamp the verified run (REQ-028)."""

    @unittest.expectedFailure
    def test_bug_016_verify_binds_run_to_artifact(self) -> None:
        """[BUG-016][Req: REQ-028] verified status binds path/digest to run.

        Desired: ``_verify_latest_metadata_backup_once`` verifies the succeeded
        run's ``local_path``/digest (or matches artifact to that run) before
        UPDATE — not ``artifacts[0]`` + newest succeeded id unbound.
        Current: verifies directory newest file then stamps newest succeeded id.
        Fix patch: quality/patches/BUG-016-fix.patch
        """
        body = _verify_latest_body()
        self.assertNotIn(
            "artifacts[0]",
            body,
            "must not verify an unbound directory newest file",
        )
        self.assertTrue(
            ("local_path" in body) or ("digest_sha256" in body),
            "verify must bind to the run's local_path or digest_sha256",
        )


class TestBug017(unittest.TestCase):
    """BUG-017: cloud-archive notify must be best-effort after Delete Marker (REQ-029)."""

    @unittest.expectedFailure
    def test_bug_017_archive_observability_best_effort(self) -> None:
        """[BUG-017][Req: REQ-029] post-marker notify must not fail-close the job.

        Desired: ``record_archive_completed`` wraps ``_notify_vault_owners`` in
        try/except (parity with ``record_automatic_cleanup_outcome``) so a
        notify failure cannot roll back the Delete Marker catalog txn or leave
        the job failed/retryable.
        Current: bare ``_notify_vault_owners`` inside the fail-closed DB path.
        Fix patch: quality/patches/BUG-017-fix.patch
        """
        completed = _record_archive_completed_body()
        notify_idx = completed.find("_notify_vault_owners")
        self.assertGreaterEqual(notify_idx, 0, "_notify_vault_owners missing")
        prelude = completed[:notify_idx]
        self.assertIn(
            "try:",
            prelude,
            "notify must be best-effort (try/except) after Delete Marker audit",
        )


class TestBug018(unittest.TestCase):
    """BUG-018: cancel recover must retain restore_state (REQ-030)."""

    @unittest.expectedFailure
    def test_bug_018_cancel_preserves_restore_state(self) -> None:
        """[BUG-018][Req: REQ-030] cancel must not wipe Glacier restore_state.

        Desired: recover cancel does not call ``clear_restore_state_for_jobs``.
        Current: cancel always clears restore_state/restore_expiry.
        Fix patch: quality/patches/BUG-018-fix.patch
        """
        body = _cancel_recover_body()
        self.assertNotIn(
            "clear_restore_state_for_jobs",
            body,
            "cancel must not erase non-cancellable RestoreObject state",
        )


def _oidc_link_body() -> str:
    start = MAIN_PY.index("def oidc_link")
    end = MAIN_PY.index("\ndef _resolve_invite_id", start)
    return MAIN_PY[start:end]


def _update_user_body() -> str:
    start = MAIN_PY.index("def update_user")
    end = MAIN_PY.index("\ndef admin_vaults", start)
    return MAIN_PY[start:end]


def _redeem_invite_body() -> str:
    invites = (REPO_ROOT / "app" / "invites.py").read_text(encoding="utf-8")
    start = invites.index("def redeem_invite")
    end = invites.index("\ndef resolve_invite", start)
    return invites[start:end]


def _postgres_verify_body() -> str:
    start = METADATA_PY.index("def _verify_postgres_dump_isolated")
    end = METADATA_PY.index("\ndef _row_run", start)
    return METADATA_PY[start:end]


class TestBug019(unittest.TestCase):
    """BUG-019: temp_database verify must not ok when tables unproven (REQ-031)."""

    @unittest.expectedFailure
    def test_bug_019_temp_database_requires_proven_counts(self) -> None:
        """[BUG-019][Req: REQ-031] temp_database mode must fail closed without counts.

        Desired: after createdb succeeds, if psql COUNT cannot prove users/vaults/
        alembic_version, raise BackupError (or ok:False) — do not return ok:True
        with null counts under verification_mode=temp_database.
        Current: accepts pg_restore rc 0/1 then returns ok:True even when counts
        stay None (metadata_backups.py:458-500). Distinct from rejected list-only
        former BUG-003.
        Fix patch: quality/patches/BUG-019-fix.patch
        Promoted from: DC-011
        """
        from app.services import metadata_backups as mb

        list_ok = MagicMock(returncode=0, stderr=b"", stdout=b"")
        created_ok = MagicMock(returncode=0, stderr=b"", stdout=b"")
        restore_soft = MagicMock(returncode=1, stderr=b"WARNING: role missing", stdout=b"")
        psql_fail = MagicMock(
            returncode=1,
            stderr="ERROR: relation \"users\" does not exist\n",
            stdout="",
        )
        drop_ok = MagicMock(returncode=0, stderr=b"", stdout=b"")

        with patch.object(mb.subprocess, "run", side_effect=[
            list_ok, created_ok, restore_soft, psql_fail, drop_ok
        ]):
            with tempfile.TemporaryDirectory() as tmp:
                with self.assertRaises(mb.BackupError):
                    mb._verify_postgres_dump_isolated(b"not-a-real-dump", Path(tmp))

    @unittest.expectedFailure
    def test_bug_019_temp_database_source_rejects_null_count_success(self) -> None:
        """[BUG-019][Req: REQ-031] source must reject null counts in temp_database path.

        Desired: after the count query, code raises when user_count/vault_count/
        schema_revision remain None under temp_database (explicit null guard).
        Current: unconditional ``\"ok\": True`` return after optional parse.
        """
        body = _postgres_verify_body()
        # Intentional list-only fallback must remain (former BUG-003 rejected).
        self.assertIn("pg_restore_list", body)
        temp_idx = body.find('"temp_database"')
        self.assertGreaterEqual(temp_idx, 0)
        # Before returning temp_database ok, counts must be explicitly validated.
        prelude = body[:temp_idx]
        self.assertIn(
            "user_count is None",
            prelude,
            "temp_database success path must explicitly guard null user_count",
        )


class TestBug020(unittest.TestCase):
    """BUG-020: last-admin deactivate must be race-safe (REQ-032)."""

    @unittest.expectedFailure
    def test_bug_020_last_admin_guard_is_atomic_with_update(self) -> None:
        """[BUG-020][Req: REQ-032] last-admin invariant must not be check-then-act.

        Desired: deactivating an admin uses a single transaction and/or a
        conditional UPDATE that refuses to leave zero active admins.
        Current: COUNT in one ``with db()`` then UPDATE in another
        (main.py:2670-2700) with no last-admin predicate on UPDATE.
        Fix patch: quality/patches/BUG-020-fix.patch
        Promoted from: DC-006
        """
        body = _update_user_body()
        self.assertIn("At least one administrator must remain active", body)
        # The UPDATE that sets active must itself encode the last-admin guard
        # (subquery / HAVING / FOR UPDATE in the same with-block as the mutate).
        update_idx = body.find("UPDATE users SET")
        self.assertGreaterEqual(update_idx, 0)
        update_sql = body[update_idx : update_idx + 400]
        self.assertTrue(
            ("COUNT(" in update_sql)
            or ("active_admins" in body[body.rfind("with db()", 0, update_idx) : update_idx + 50]
                and "FOR UPDATE" in body)
            or ("SELECT COUNT" in update_sql),
            "UPDATE must be conditional on last-admin count or share a locked txn",
        )


class TestBug021(unittest.TestCase):
    """BUG-021: OIDC self-link invite creation requires recent reauth (REQ-033)."""

    @unittest.expectedFailure
    def test_bug_021_oidc_link_requires_recent_reauth(self) -> None:
        """[BUG-021][Req: REQ-033] self-link must gate invite creation on reauth.

        Desired: ``oidc_link`` Depends includes ``require_recent_reauth`` (ADR-0005
        lists invite creation as a sensitive action; ADR-0003 self-link IS invite
        issuance). Current: only ``current_user`` (main.py:1079-1096).
        Fix patch: quality/patches/BUG-021-fix.patch
        Promoted from: DC-013
        """
        body = _oidc_link_body()
        self.assertIn("create_invite", body)
        self.assertIn(
            "require_recent_reauth",
            body,
            "self-link invite creation must require recent reauthentication",
        )


class TestBug022(unittest.TestCase):
    """BUG-022: invite redeem must be single-use under concurrency (REQ-034)."""

    @unittest.expectedFailure
    def test_bug_022_redeem_update_guards_unredeemed(self) -> None:
        """[BUG-022][Req: REQ-034] redeem UPDATE must refuse already-redeemed rows.

        Desired: ``UPDATE invites ... WHERE id=%s AND redeemed_at IS NULL``
        (or equivalent) so concurrent redeemers cannot both succeed / clobber.
        Current: UPDATE by id only after a non-locking SELECT
        (invites.py:99-106) — TOCTOU vs ADR-0003 single-use.
        Fix patch: quality/patches/BUG-022-fix.patch
        Promoted from: DC-002
        """
        body = _redeem_invite_body()
        self.assertIn("UPDATE invites", body)
        self.assertRegex(
            body,
            r"redeemed_at\s+IS\s+NULL",
            "redeem UPDATE must condition on redeemed_at IS NULL",
        )


if __name__ == "__main__":
    unittest.main()
