# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-07-23 · Project: FrostVault
"""Functional tests derived from quality/REQUIREMENTS.md and QUALITY.md scenarios.

Run from repo root:
  PYTHONPATH=. .venv/bin/python -m unittest discover -s quality -p 'test_functional.py' -v
"""
from __future__ import annotations

import inspect
import ipaddress
import unittest
from dataclasses import replace
from pathlib import Path
from unittest.mock import patch

from app import breakglass
from app.config import settings
from app.database import HEAD_SCHEMA_REVISION, DatabaseSchemaError
from app.proxy import resolve_client_ip
from app.services import operation_policies, vault_recovery, vault_roles
from app.services.vault_recovery import RecoveryCustodyRequired


REPO_ROOT = Path(__file__).resolve().parents[1]
STORAGE_PY = (REPO_ROOT / "app" / "storage.py").read_text(encoding="utf-8")
SESSIONS_PY = (REPO_ROOT / "app" / "sessions.py").read_text(encoding="utf-8")
METADATA_PY = (
    REPO_ROOT / "app" / "services" / "metadata_backups.py"
).read_text(encoding="utf-8")
README = (REPO_ROOT / "README.md").read_text(encoding="utf-8")


def _patch_break_glass_cidrs(raw: str):
    patched = replace(settings, break_glass_allowed_cidrs=raw)
    return patch("app.breakglass.settings", patched)


class TestSpecRequirements(unittest.TestCase):
    """Spec requirements — one focused check per REQ where automatable."""

    def test_req_001_version_id_required_and_pinned_in_source(self) -> None:
        """[Req: REQ-001] Exact VersionId required; crypt and plain pins present."""
        self.assertIn(
            'raise RuntimeError("Exact S3 VersionId is required for recovery")',
            STORAGE_PY,
        )
        self.assertIn("--s3-version-id=", STORAGE_PY)
        self.assertIn("VersionId=provider_version_id", STORAGE_PY)
        # Docstring may wrap across lines; match the lead phrase.
        self.assertIn("Path-only current-object downloads are", STORAGE_PY)
        self.assertIn("forbidden because they can return a different object version", STORAGE_PY)

    def test_req_002_recover_branch_lacks_status_conjunct(self) -> None:
        """[Req: REQ-002] Recover branch currently has no status whitelist (known gap)."""
        # Document current code shape for Phase 3: peers have status checks; recover does not.
        self.assertIn(
            'elif job["action"] == "recover":',
            STORAGE_PY,
        )
        self.assertIn(
            'elif job["action"] == "free-space" and job["status"] == "queued":',
            STORAGE_PY,
        )
        # Mechanical expectation for the requirement (desired): status set should appear.
        # This asserts the peer pattern exists so the gap is measurable.
        self.assertIn(
            'job["action"] == "upload" and job["status"] in {"queued", "retrying"}',
            STORAGE_PY,
        )

    def test_req_003_operator_not_owner_and_readme_conflict(self) -> None:
        """[Req: REQ-003] Operators are not owners; README Users over-claims free-space."""
        self.assertFalse(vault_roles.is_owner("operator"))
        self.assertTrue(vault_roles.is_owner("owner"))
        self.assertIn("free local space", README.lower())
        # Users section claims operators can free local space (conflict).
        self.assertRegex(
            README,
            r"operator` can upload, free\s+local space, and recover",
        )
        # Local cleanup safety correctly restricts to owners.
        self.assertIn("for owners", README)

    def test_req_006_break_glass_fail_closed_and_loopback(self) -> None:
        """[Req: REQ-006] Missing IP denied; loopback allowed with empty CIDRs."""
        with _patch_break_glass_cidrs(""):
            self.assertFalse(breakglass.is_break_glass_allowed(None))
            self.assertFalse(breakglass.is_break_glass_allowed("not-an-ip"))
            self.assertTrue(breakglass.is_break_glass_allowed("127.0.0.1"))
            self.assertFalse(breakglass.is_break_glass_allowed("203.0.113.5"))

    def test_req_007_untrusted_peer_ignores_forwarded_for(self) -> None:
        """[Req: REQ-007] XFF ignored when peer is not a Trusted Proxy."""
        trusted = [ipaddress.ip_network("10.0.0.0/8")]
        resolved = resolve_client_ip(
            peer="203.0.113.9",
            forwarded_for="10.0.0.5",
            trusted_proxies=trusted,
        )
        self.assertEqual(resolved, "203.0.113.9")

    def test_req_007_trusted_peer_uses_rightmost_untrusted_hop(self) -> None:
        """[Req: REQ-007] Trusted peer + XFF selects client hop."""
        trusted = [ipaddress.ip_network("10.0.0.0/8")]
        resolved = resolve_client_ip(
            peer="10.0.0.1",
            forwarded_for="203.0.113.50, 10.0.0.2",
            trusted_proxies=trusted,
        )
        self.assertEqual(resolved, "203.0.113.50")

    def test_req_010_head_schema_constant(self) -> None:
        """[Req: REQ-010] HEAD_SCHEMA_REVISION matches expected migration id."""
        self.assertEqual(HEAD_SCHEMA_REVISION, "0021_local_retention")
        self.assertTrue(issubclass(DatabaseSchemaError, RuntimeError))

    def test_req_011_custody_message_has_no_secret_material(self) -> None:
        """[Req: REQ-011] RecoveryCustodyRequired message does not embed secrets."""
        vault = {
            "id": 1,
            "encryption_mode": "crypt",
            "recovery_custody_confirmed_at": None,
        }
        # Force the helper path via public API when custody required.
        if hasattr(vault_recovery, "vault_requires_recovery_custody"):
            with patch(
                "app.services.vault_recovery.vault_requires_recovery_custody",
                return_value=True,
            ):
                with self.assertRaises(RecoveryCustodyRequired) as ctx:
                    vault_recovery.require_upload_custody(vault)
                message = str(ctx.exception).lower()
                self.assertNotIn("password", message)
                self.assertNotIn("secret=", message)
                self.assertIn("custody", message)

    def test_req_012_operating_window_start_before_end(self) -> None:
        """[Req: REQ-012] Overnight / inverted windows rejected."""
        with self.assertRaises(ValueError):
            operation_policies._normalize_windows(
                [{"weekday": 1, "start": "22:00", "end": "06:00"}]
            )
        with self.assertRaises(ValueError):
            operation_policies._normalize_windows(
                [{"weekday": 1, "start": "09:00", "end": "09:00"}]
            )
        ok = operation_policies._normalize_windows(
            [{"weekday": 1, "start": "09:00", "end": "17:00"}]
        )
        self.assertEqual(ok[0]["start"], "09:00")

    def test_req_016_can_operate_matrix(self) -> None:
        """[Req: REQ-016] Owner and operator can operate; viewer cannot."""
        self.assertTrue(vault_roles.can_operate("owner"))
        self.assertTrue(vault_roles.can_operate("operator"))
        self.assertFalse(vault_roles.can_operate("viewer"))

    def test_req_017_viewer_not_owner(self) -> None:
        """[Req: REQ-017] Viewer is read-only at role helpers."""
        self.assertFalse(vault_roles.is_owner("viewer"))
        self.assertFalse(vault_roles.can_operate("viewer"))
        self.assertTrue(vault_roles.is_valid_role("viewer"))


class TestFitnessScenarios(unittest.TestCase):
    """1:1 mapping to QUALITY.md fitness scenarios."""

    def test_scenario_1_cloud_archive_delete_object_omits_version_id(self) -> None:
        """Scenario 1: process_cloud_archive delete_object has no VersionId kwarg in source."""
        start = STORAGE_PY.index("def process_cloud_archive")
        end = STORAGE_PY.index("\ndef process_cloud_purge", start)
        body = STORAGE_PY[start:end]
        self.assertIn("delete_object(", body)
        self.assertNotIn("VersionId=", body)

    def test_scenario_2_readme_users_vs_owner_matrix(self) -> None:
        """Scenario 2: README Users vs is_owner matrix drift."""
        self.assertFalse(vault_roles.is_owner("operator"))
        self.assertIn("operator` can upload, free", README)

    def test_scenario_3_recover_dispatcher_gap(self) -> None:
        """Scenario 3: recover action branch lacks status guard."""
        start = STORAGE_PY.index("def process_job")
        end = STORAGE_PY.index("\ndef process_jobs_once", start)
        body = STORAGE_PY[start:end]
        self.assertIn('elif job["action"] == "recover":', body)
        # Immediately following line should call process_recover without status and.
        recover_idx = body.index('elif job["action"] == "recover":')
        snippet = body[recover_idx : recover_idx + 80]
        self.assertIn("process_recover(job)", snippet)
        self.assertNotIn("status", snippet.split("\n")[0])

    def test_scenario_4_list_only_mode_marked_in_source(self) -> None:
        """Scenario 4: createdb failure returns ok True with pg_restore_list mode."""
        self.assertIn('"verification_mode": "pg_restore_list"', METADATA_PY)
        self.assertIn('"ok": True', METADATA_PY)
        self.assertIn("createdb", METADATA_PY)

    def test_scenario_5_untrusted_peer_ignores_xff(self) -> None:
        """Scenario 5: forged XFF from untrusted peer does not win."""
        trusted = [ipaddress.ip_network("192.168.0.0/16")]
        resolved = resolve_client_ip(
            peer="198.51.100.10",
            forwarded_for="127.0.0.1",
            trusted_proxies=trusted,
        )
        self.assertEqual(resolved, "198.51.100.10")
        with _patch_break_glass_cidrs("127.0.0.1/32"):
            self.assertFalse(breakglass.is_break_glass_allowed(resolved))

    def test_scenario_6_restore_claimed_helper_exists(self) -> None:
        """Scenario 6: restore_claimed_local_copy exists and is used by free-space path."""
        self.assertIn("def restore_claimed_local_copy", STORAGE_PY)
        free_start = STORAGE_PY.index("def process_free_space")
        free_end = STORAGE_PY.index("\ndef download_exact_version_plaintext", free_start)
        self.assertIn("restore_claimed_local_copy", STORAGE_PY[free_start:free_end])

    def test_scenario_7_crypt_and_plain_version_pins(self) -> None:
        """Scenario 7: both crypt flag and boto3 VersionId appear in download helper."""
        start = STORAGE_PY.index("def download_exact_version_plaintext")
        end = STORAGE_PY.index("\ndef process_recover", start)
        body = STORAGE_PY[start:end]
        self.assertIn("--s3-version-id=", body)
        self.assertIn("VersionId=provider_version_id", body)

    def test_scenario_8_csrf_query_omits_session_version(self) -> None:
        """Scenario 8: csrf_token_for SQL does not select session_version (gap)."""
        start = SESSIONS_PY.index("def csrf_token_for")
        end = SESSIONS_PY.index("\ndef mark_reauthenticated", start)
        body = SESSIONS_PY[start:end]
        self.assertIn("csrf_token", body)
        self.assertNotIn("session_version", body)
        # resolve_session does check session_version.
        resolve = SESSIONS_PY[
            SESSIONS_PY.index("def resolve_session") : SESSIONS_PY.index(
                "def csrf_token_for"
            )
        ]
        self.assertIn("session_version", resolve)

    def test_scenario_9_overnight_window_rejected(self) -> None:
        """Scenario 9: overnight span raises ValueError."""
        with self.assertRaises(ValueError) as ctx:
            operation_policies._normalize_windows(
                [{"weekday": 0, "start": "22:00", "end": "06:00"}]
            )
        self.assertIn("before end", str(ctx.exception))

    def test_scenario_10_schema_gate_message_contract(self) -> None:
        """Scenario 10: DatabaseSchemaError is the refuse-start signal type."""
        err = DatabaseSchemaError("Database schema is not current")
        self.assertIn("not current", str(err))


class TestBoundaries(unittest.TestCase):
    """Boundaries and defensive patterns."""

    def test_break_glass_empty_string_ip_denied(self) -> None:
        with _patch_break_glass_cidrs("10.0.0.0/8"):
            self.assertFalse(breakglass.is_break_glass_allowed(""))

    def test_resolve_client_ip_missing_peer(self) -> None:
        self.assertIsNone(
            resolve_client_ip(peer=None, forwarded_for="1.2.3.4", trusted_proxies=[])
        )

    def test_resolve_client_ip_all_hops_trusted_returns_first(self) -> None:
        trusted = [ipaddress.ip_network("10.0.0.0/8")]
        resolved = resolve_client_ip(
            peer="10.0.0.9",
            forwarded_for="10.0.0.1, 10.0.0.2",
            trusted_proxies=trusted,
        )
        self.assertEqual(resolved, "10.0.0.1")

    def test_operating_window_rejects_bad_weekday(self) -> None:
        with self.assertRaises(ValueError):
            operation_policies._normalize_windows(
                [{"weekday": 7, "start": "09:00", "end": "10:00"}]
            )

    def test_valid_roles_closed_set(self) -> None:
        for role in ("owner", "operator", "viewer"):
            self.assertTrue(vault_roles.is_valid_role(role))
        self.assertFalse(vault_roles.is_valid_role("admin"))

    def test_download_helper_signature_requires_version_id(self) -> None:
        from app import storage

        sig = inspect.signature(storage.download_exact_version_plaintext)
        self.assertIn("provider_version_id", sig.parameters)

    def test_cloud_archive_source_records_marker_version(self) -> None:
        start = STORAGE_PY.index("def process_cloud_archive")
        end = STORAGE_PY.index("\ndef process_cloud_purge", start)
        body = STORAGE_PY[start:end]
        self.assertIn("marker_version", body)
        self.assertIn("record_delete_marker", body)

    def test_process_job_cancelled_short_circuit_in_source(self) -> None:
        start = STORAGE_PY.index("def process_job")
        end = STORAGE_PY.index("\ndef process_jobs_once", start)
        self.assertIn('current["status"] == "cancelled"', STORAGE_PY[start:end])


if __name__ == "__main__":
    unittest.main()
