#!/usr/bin/env bash
# Executable triage probes for FrostVault Phase 4 Council of Three.
# Generated by Quality Playbook v1.5.6 — 2026-07-23
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"
PYTHON="${ROOT}/.venv/bin/python"
export PYTHONPATH="$ROOT"

echo "=== Pre-audit spot-check extracts ==="
"$PYTHON" - <<'PY'
from pathlib import Path
readme = Path("README.md").read_text(encoding="utf-8").splitlines()
print("Claim: README says operators can free local space")
print(f"Actual README.md lines 19-20: {readme[18].strip()}")
print(f"Actual README.md lines 20: {readme[19].strip() if len(readme)>19 else ''}")
storage = Path("app/storage.py").read_text(encoding="utf-8").splitlines()
print("Claim: process_cloud_archive pins VersionId on delete")
for i in range(2098, 2103):
    print(f"Actual app/storage.py line {i+1}: {storage[i].rstrip()}")
print("Result: CLAIM FALSE — delete_object has no VersionId")
for i in range(2222, 2225):
    print(f"Actual process_job recover line {i+1}: {storage[i].rstrip()}")
PY

echo "=== Confirmation probes (BUG-001..005) ==="
"$PYTHON" - <<'PY'
from pathlib import Path
import re
storage = Path("app/storage.py").read_text(encoding="utf-8")
# BUG-001 confirmation: recover branch lacks status
m = re.search(r'elif job\["action"\] == "recover":\n\s+process_recover', storage)
assert m, "recover branch pattern missing"
line = storage[:m.start()].count("\n") + 1
print(f"BUG-001 CONFIRM line {line}: bare recover branch (no status conjunct)")

# BUG-002 confirmation
body_start = storage.index("def process_cloud_archive")
body_end = storage.index("\ndef process_cloud_purge", body_start)
body = storage[body_start:body_end]
assert "delete_object(" in body
assert "VersionId" not in body[body.index("delete_object("):body.index("delete_object(")+120]
print("BUG-002 CONFIRM: delete_object call omits VersionId; no Head/compare before delete")

# BUG-003 confirmation
meta = Path("app/services/metadata_backups.py").read_text(encoding="utf-8")
assert '"verification_mode": "pg_restore_list"' in meta
assert '"ok": True' in meta[meta.index("created.returncode != 0"):meta.index('"verification_mode": "pg_restore_list"')+80]
consumer = storage[storage.index("def _verify_latest_metadata_backup_once"):storage.index("\nasync def background_loop")]
assert "verification_mode" not in consumer or "temp_database" not in consumer
print("BUG-003 CONFIRM: list-only ok True + consumer ignores verification_mode")

# BUG-004 confirmation
sess = Path("app/sessions.py").read_text(encoding="utf-8")
csrf = sess[sess.index("def csrf_token_for"):sess.index("\ndef mark_reauthenticated")]
assert "session_version" not in csrf
print("BUG-004 CONFIRM: csrf_token_for omits session_version")

# BUG-005 confirmation
readme_lines = Path("README.md").read_text(encoding="utf-8").splitlines()
users_bullet = (readme_lines[18] + " " + readme_lines[19]).lower()
assert "operator" in users_bullet and "free" in users_bullet and "local space" in users_bullet
from app.services.vault_roles import is_owner
assert is_owner("operator") is False
print("BUG-005 CONFIRM: README.md:19-20 overclaims; is_owner(operator)=False")
print("ALL BUG-001..005 independently reconfirmed")
PY

echo "=== Minority A — REQ-012 lexicographic windows ==="
"$PYTHON" - <<'PY'
from app.services.operation_policies import _normalize_windows
# Confirmation proof: inverted non-padded window is wrongly accepted (BUG exists)
accepted = False
try:
    _normalize_windows([{"weekday": 1, "start": "10:00", "end": "9:30"}])
    accepted = True
except ValueError:
    pass
assert accepted, "expected inverted non-padded window to be wrongly accepted on current code"
# Desired correct behavior assertion (fails today → documents bug):
# Desired: this MUST raise. Current: does not. Expected-failure regression covers it.
print("MINORITY-A CONFIRMED: start=10:00 end=9:30 accepted via string compare (line 96-97)")
print("Evidence lex: '10:00' >= '9:30' ==", "10:00" >= "9:30")
print("Evidence line 96: `if start >= end:` compares raw strings after int shape parse")
PY

echo "=== Minority B — REQ-009 startup deletes free-space claims ==="
"$PYTHON" - <<'PY'
from pathlib import Path
from app.storage import is_restore_temporary_name, CLEANUP_TEMPORARY_RE
name = ".photo.jpg.cleanup-" + ("ab" * 16) + ".tmp"
assert CLEANUP_TEMPORARY_RE.fullmatch(name)
assert is_restore_temporary_name(name)
main = Path("app/main.py").read_text(encoding="utf-8")
assert main.index("cleanup_abandoned_restore_files()") < main.index("reconcile_interrupted_jobs()")
storage = Path("app/storage.py").read_text(encoding="utf-8")
cleanup = storage[storage.index("def cleanup_abandoned_restore_files"):storage.index("\ndef reconcile_interrupted_jobs")]
assert "is_restore_temporary_name" in cleanup
recon = storage[storage.index('if job["action"] == "free-space":'):storage.index("connection.execute(", storage.index('if job["action"] == "free-space":')+200)+400]
assert "restore_claimed_local_copy" not in storage[storage.index('if job["action"] == "free-space":'):storage.index("summary[\"completed\"] += 1")]
print("MINORITY-B CONFIRMED: cleanup claims match is_restore_temporary_name; cleanup runs before reconcile;")
print("reconcile missing-path path marks completed without restore_claimed_local_copy")
print("Evidence app/storage.py:353-357 includes CLEANUP_TEMPORARY_RE")
print("Evidence app/storage.py:1028 unlinks is_restore_temporary_name entries")
print("Evidence app/main.py:160-161 cleanup before reconcile")
print("Evidence app/storage.py:1092-1109 missing path → completed")
PY

echo "=== Minority B upload HeadObject vs REQ-001 (rejection) ==="
"$PYTHON" - <<'PY'
from pathlib import Path
req = Path("quality/REQUIREMENTS.md").read_text(encoding="utf-8")
# Rejection proof: REQ-001 CoS are recovery-download scoped, not upload HeadObject
section = req[req.index("### REQ-001:"):req.index("### REQ-002:")]
assert "download_exact_version" in section or "recovering" in section.lower()
assert "When recovering" in section or "recovering a file" in section
assert "head_object" not in section.lower()
assert "Upload" not in section.split("Conditions of satisfaction")[1].split("Alternative")[0]
print("MINORITY upload-HeadObject FALSE-POSITIVE vs REQ-001: requirement scopes recovery downloads only")
print("Evidence REQ-001 summary quotes recovery download surfaces; CoS 1-4 name VersionId on get/rclone recover path")
PY

echo "=== All triage probes completed ==="
